.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/usage-question.md

*Issue #, if available:*
*Description of changes:*

Add GitHub issue templates

---

markdown/tests/flutter/flutter_step2.md
markdown/tests/flutter/flutter_step4.md

*Description of changes:*
Flutter:
- Shortened overall instructions
- Fixed instructional bugs

Flutter: fixed some instruction bugs and shortened text

---

markdown/tests/flutter/flutter_relationship.md

Signed-off-by: Kilo Loco <kyle@kiloloco.com>
*Issue #, if available:*
n/a
*Description of changes:*
Completed documentation for Flutter Relationship step

Complete Flutter relationship step

---

markdown/tests/flutter/flutter_step4.md

*Issue #, if available:* https://github.com/aws-amplify/docs/pull/3011 https://github.com/aws-amplify/amplify-flutter/issues/359
*Description of changes:* Add workaround for customers using flutter V2

Add workaround for customers using flutter V2

---

CONTRIBUTING.md
README.md

*Description of changes:*
- add `CONTRIBUTING.md`
- remove stale link in readme

chore(readme + contrib): add CONTRIBUTING + remove stale link in readme

---

markdown/tests/flutter/flutter_step4.md

Updates flutter snippets to reflect null safety release to version 0.2.0

chore(flutter): update flutter snippets to reflect null safety release

---

markdown/tests/flutter/flutter_step4.md

Bumped Flutter to version 0.4.0

Bumped Flutter version number

---

markdown/tests/react_native/react_native_step3.md
markdown/tests/web/angular_step3.md
markdown/tests/web/react_step3.md
markdown/tests/web/vue_step3.md

adding back creation steps in the sandbox

---

markdown/tests/flutter/flutter_step4.md
markdown/tests/react_native/react_native_step4.md
markdown/tests/web/angular_step2.md
markdown/tests/web/angular_step3.md
markdown/tests/web/react_step3.md
markdown/tests/web/react_step4.md
markdown/tests/web/react_sync.md
markdown/tests/web/vue_step3.md
markdown/tests/web/vue_step4.md
markdown/tests/web/vue_step5.md

Updated to Studio to align to getting started guide

Updated to Studio to align to getting started guide

---

markdown/tests/flutter/flutter_step4.md

Updating Flutter version

---

markdown/tests/android/java_step5_data_code_api.md
markdown/tests/android/kotlin_step5_data_code_api.md
markdown/tests/flutter/flutter_step5_data_code_api.md
markdown/tests/ios/swift_step5_data_code_api.md
markdown/tests/react_native/react_native_step5_data_code_api.md
markdown/tests/web/react_step5_data_code_api.md

feat(conflict-resolution): add API code snippets

---

README.md

added Studio rename

---

.github/ISSUE_TEMPLATE/1.bug_report.yaml

adds Project Identifier section from [Amplify CLI bug report template](https://github.com/aws-amplify/amplify-cli/blob/dev/.github/ISSUE_TEMPLATE/1.bug_report.yaml)
n/a

chore: add diagnose project ID to bug template

---

.github/ISSUE_TEMPLATE/1.bug_report.yaml

Requires input for `App Id` in bug template

chore: make "app id" a required bug report input field

---

.github/workflows/issue-pending-response.yml

Github workflow that removes pending response label on issues where customer has responded.

feat: add github action to remove pending-response labels

---

markdown/tests/web/react_relationship.md

- Changing the relationship docs to reflect v5 capabilities

Updating docs to reflect Amplify JS v5 instructions

---

.github/workflows/closed-issue-message.yml

This workflow adds auto messages for closed issues enabling customers to understand that commenting on a closed issue can be hard to track and customer should open a new issue.

add: message for closed issues

---

.github/ISSUE_TEMPLATE/3.feature_request.yaml

updates Feature request template to provide better ask from users on their use case.

chore: update fr template

---

markdown/categories/graphql-api/template.md

Removes private video in GraphQL API tab in Sandbox

remove graphql youtube video

---

markdown/storage/web/react.md
markdown/tests/react_native/react_native_step4.md
markdown/tests/react_native/react_native_step5_data_code.md
markdown/tests/react_native/react_native_step5_data_code_api.md
markdown/tests/react_native/react_native_sync.md
markdown/tests/web/angular_step4.md
markdown/tests/web/angular_step5_data_code.md
markdown/tests/web/angular_step5_data_code_api.md
markdown/tests/web/react_step4.md
markdown/tests/web/react_step5_auth_code.md
markdown/tests/web/react_step5_data_code.md
markdown/tests/web/react_step5_data_code_api.md
markdown/tests/web/react_sync.md
markdown/tests/web/vue_step4.md
markdown/tests/web/vue_step5_data_code.md
markdown/tests/web/vue_step5_data_code_api.md

Added JavaScript v6
